export default {
    // User
    LOGIN_REQUEST: '@@user/LOGIN_REQUEST',
    LOGIN_FAILURE: '@@user/LOGIN_FAILURE',
    LOGIN_SUCCESS: '@@user/LOGIN_SUCCESS',

    // landing
    FETCH_REQUEST: '@@login/FETCH_REQUEST',
    FETCH_FAILURE: '@@login/FETCH_FAILURE',

    // Sign up
    SIGNUP_FAILURE: '@@user/SIGNUP_FAILURE',

    // File
    FETCH_FILES_SUCCESS: '@@file/FETCH_FILES_SUCCESS',
    FETCH_FILES_FAILURE: '@@file/FETCH_FILES_FAILURE',
    FETCH_FILE_SUCCESS: '@@file/FETCH_FILE_SUCCESS',
    FETCH_FILE_FAILURE: '@@file/FETCH_FILE_FAILURE',
    UPDATE_FILE_SUCCESS: '@@file/UPDATE_FILE_SUCCESS',
    UPDATE_FILE_FAILURE: '@@file/UPDATE_FILE_FAILURE',

    FETCH_SHARES_SUCCESS: '@@shares/FETCH_SHARES_SUCCESS',
    FETCH_SHARES_FAILURE: '@@shares/FETCH_SHARES_FAILURE',
    FETCH_SHARE_FILE_SUCCESS: '@@shares_file/FETCH_SHARE_FILE_SUCCESS',
    FETCH_SHARE_FILE_FAILURE: '@@shares_file/FETCH_SHARE_FILE_FAILURE',

    FETCH_PDF_SUCCESS: '@@file/FETCH_FILE_SUCCESS',
    FETCH_PDF_FAILURE: '@@file/FETCH_FILE_FAILURE',

    // Comment
    CREATE_COMMENT_SUCCESS: '@@file/CREATE_COMMENT_SUCCESS',
    RECEIVE_COMMENT: '@@file/RECEIVE_COMMENT',

    //Notifcation
    FETCH_NOTIFICATION_SUCCESS: '@@notification/FETCH_NOTIFICATION_SUCCESS',
    SEND_NOTIFICATION_SUCCESS: '@@notification/SEND_NOTIFICATION_SUCCESS',
    RECEIVE_NOTIFICATION: '@@notification/RECIEVE_NOTIFICATION',
}
