export default {
    // User
    LOGIN_REQUEST: '@@user/LOGIN_REQUEST',
    LOGIN_FAILURE: '@@user/LOGIN_FAILURE',
    LOGIN_SUCCESS: '@@user/LOGIN_SUCCESS',

    // landing
    FETCH_REQUEST: '@@login/FETCH_REQUEST',
    FETCH_FAILURE: '@@login/FETCH_FAILURE',

    // Sign up
    SIGNUP_FAILURE: '@@user/SIGNUP_FAILURE',

    // File
    FETCH_FILES_SUCCESS: '@@file/FETCH_FILES_SUCCESS',
    FETCH_FILES_FAILURE: '@@file/FETCH_FILES_FAILURE',
    FETCH_FILE_SUCCESS: '@@file/FETCH_FILE_SUCCESS',
    FETCH_FILE_FAILURE: '@@file/FETCH_FILE_FAILURE',

    // selected file
    SELECT_FILE: '@@selected_file/SELECT_FILE',
    SAVE_FILE: '@@selected_file/SAVE_FILE',
    ADD_BLOCK_TO_SELECTED_FILE: '@@selected_file/ADD_BLOCK_TO_SELECTED_FILE',
    REMOVE_BLOCK_FROM_SELECTED_FILE: '@@selected_file/REMOVE_BLOCK_FROM_SELECTED_FILE',
    MOVE_BLOCK_FROM_SELECTED_FILE: '@@selected_file/MOVE_BLOCK_FROM_SELECTED_FILE',

    // Comment
    CREATE_COMMENT_SUCCESS: '@@file/CREATE_COMMENT_SUCCESS',
    RECEIVE_COMMENT: '@@file/RECEIVE_COMMENT',
}
